apiVersion: batch/v1
kind: Job
metadata:
  name: cert-generator
spec:
  template:
    spec:
      containers:
      - name: generate-certs
        image: wazuh/wazuh-certs-generator:0.0.2
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-certs
  namespace: wazuh
  labels:
    app: wazuh-certs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi