apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker-0
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: worker
      sts-id: '0'
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: worker
        sts-id: '0'
      name: wazuh-manager-worker-0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: sts-id
                      operator: In
                      values:
                        - '1'
                topologyKey: kubernetes.io/hostname
      volumes:
        - name: config
          configMap:
            name: wazuh-manager-worker-0-conf
        - name: wazuh-worker-0
          persistentVolumeClaim:
            claimName: wazuh-worker-0
        - name: wazuh-sslmanager
          secret:
            secretName: wazuh-sslmanager
      containers:
        - name: wazuh-manager
          image: {{ .Values.wazuhWorker.image }}
          env:
            - name: ELASTICSEARCH_URL
              value: {{ .Values.wazuhWorker.ELASTICSEARCH_URL }}
   
          resources:
            requests:
              cpu: 200m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: wazuh-worker-0
              subPath: etc
              mountPath: /var/ossec/etc
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/sslmanager.key
              subPath: sslmanager.key
              readOnly: true
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/sslmanager.cert
              subPath: sslmanager.cert
              readOnly: true
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/rootCA.key
              subPath: rootCA.key
              readOnly: true
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/rootCA.pem
              subPath: rootCA.pem
              readOnly: true 
          ports:
            - containerPort: 1514
              name: agents-events
            - containerPort: 1516
              name: cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-worker-0
  namespace: wazuh
  labels:
    app: wazuh-worker-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
