apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-master
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: master
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: master
      name: wazuh-manager-master
    spec:   
      containers:
        - name: wazuh-manager
          image: {{ .Values.wazuhMaster.image }}
          env:
            - name: ELASTICSEARCH_URL
              value: {{ .Values.wazuhMaster.ELASTICSEARCH_URL }}
          resources:
            requests:
              cpu: 200m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          volumeMounts:
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true
            - name: wazuh-manager-master
              subPath: etc
              mountPath: /var/ossec/etc  
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/sslmanager.key
              subPath: sslmanager.key
              readOnly: true
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/sslmanager.cert
              subPath: sslmanager.cert
              readOnly: true
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/rootCA.key
              subPath: rootCA.key
              readOnly: true
            - name: wazuh-sslmanager
              mountPath: /var/ossec/data/etc/rootCA.pem
              subPath: rootCA.pem
              readOnly: true            
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1516
              name: cluster
            - containerPort: 55000
              name: api
      volumes:
      - name: wazuh-manager-master
        persistentVolumeClaim:
          claimName: wazuh-manager-master
      - name: config
        configMap:
          name: wazuh-manager-master-conf
      - name: wazuh-sslmanager
        secret:
          secretName: wazuh-sslmanager
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-master
  namespace: wazuh
  labels:
    app: wazuh-manager-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}