---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-indexer
      node-type: index
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-indexer
        node-type: index
      name: wazuh-indexer
    spec:   
      containers:
        - name: wazuh-indexer
          image: wazuh/wazuh-indexer:{{ .Values.wazuh.tag }}
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: bootstrap.memory_lock
              value: "true"
            - name: NODE_NAME
              value: "wazuh-indexer"
            - name: CLUSTER_INITIAL_MASTER_NODES
              value: "wazuh-indexer"
            - name: CLUSTER_NAME
              value: "wazuh-cluster"
            - name: PATH_DATA
              value: /var/lib/wazuh-indexer
            - name: PATH_LOGS
              value: /var/log/wazuh-indexer
            - name: HTTP_PORT
              value: 9200-9299
            - name: TRANSPORT_TCP_PORT
              value: 9300-9399
            - name: COMPATIBILITY_OVERRIDE_MAIN_RESPONSE_VERSION
              value: "true"
            - name: PLUGINS_SECURITY_SSL_HTTP_PEMCERT_FILEPATH
              value: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
            - name: PLUGINS_SECURITY_SSL_HTTP_PEMKEY_FILEPATH
              value: /usr/share/wazuh-indexer/certs/wazuh.indexer.key
            - name: PLUGINS_SECURITY_SSL_HTTP_PEMTRUSTEDCAS_FILEPATH
              value: /usr/share/wazuh-indexer/certs/root-ca.pem
            - name: PLUGINS_SECURITY_SSL_TRANSPORT_PEMCERT_FILEPATH
              value: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
            - name: PLUGINS_SECURITY_SSL_TRANSPORT_PEMKEY_FILEPATH
              value: /usr/share/wazuh-indexer/certs/wazuh.indexer.key
            - name: PLUGINS_SECURITY_SSL_TRANSPORT_PEMTRUSTEDCAS_FILEPATH
              value: /usr/share/wazuh-indexer/certs/root-ca.pem
            - name: PLUGINS_SECURITY_SSL_HTTP_ENABLED
              value: "true"
            - name: PLUGINS_SECURITY_SSL_TRANSPORT_ENFORCE_HOSTNAME_VERIFICATION
              value: "false"
            - name: PLUGINS_SECURITY_SSL_TRANSPORT_RESOLVE_HOSTNAME
              value: "false"
            - name: PLUGINS_SECURITY_AUTHCZ_ADMIN_DN
              value: "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
            - name: PLUGINS_SECURITY_CHECK_SNAPSHOT_RESTORE_WRITE_PRIVILEGES
              value: "true"
            - name: PLUGINS_SECURITY_ENABLE_SNAPSHOT_RESTORE_PRIVILEGE
              value: "true"
            - name: PLUGINS_SECURITY_NODES_DN
              value: "CN=wazuh.indexer,OU=Wazuh,O=Wazuh,L=California,C=US"
            - name: PLUGINS_SECURITY_RESTAPI_ROLES_ENABLED
              value: '["all_access", "security_rest_api_access"]'
            - name: PLUGINS_SECURITY_SYSTEM_INDICES_ENABLED
              value: "true"
            - name: PLUGINS_SECURITY_SYSTEM_INDICES_INDICES
              value: '[".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]'
            - name: PLUGINS_SECURITY_ALLOW_DEFAULT_INIT_SECURITYINDEX
              value: "true"
            - name: CLUSTER_ROUTING_ALLOCATION_DISK_THRESHOLD_ENABLED
              value: "false"
          resources:
            requests:
              cpu: 200m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          volumeMounts:
            -  name: opensearch-yml
               mountPath: /usr/share/wazuh-indexer/opensearch.yml
               subPath: opensearch.yml
            - name: wazuh-indexer-data
              mountPath: /var/lib/wazuh-indexer
            - name: wazuh-root
              mountPath: /usr/share/wazuh-indexer/certs/root-ca.pem
              subPath: root-ca.pem
            - name: wazuh-indexer
              subPath: wazuh-indexer.wazuh.svc-key.pem
              mountPath: /usr/share/wazuh-indexer/certs/wazuh.indexer.key
            - name: wazuh-indexer
              mountPath: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
              subPath: wazuh-indexer.wazuh.svc.pem
            - name: wazuh-admin
              mountPath: /usr/share/wazuh-indexer/certs/admin.pem
              subPath: admin.pem
            - name: wazuh-admin
              mountPath: /usr/share/wazuh-indexer/certs/admin-key.pem
              subPath: admin-key.pem
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1516
              name: cluster
            - containerPort: 55000
              name: api
      volumes:
      - name: wazuh-indexer-data
        persistentVolumeClaim:
          claimName: wazuh-indexer-data
      - name: opensearch-yml
        configMap:
          name: opensearch-yml
      - name: wazuh-root
        secret:
          secretName: wazuh-root
      - name: wazuh-indexer
        secret:
          secretName: wazuh-indexer
      - name: wazuh-admin
        secret:
          secretName: wazuh-admin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer-data
  namespace: wazuh
  labels:
    app: wazuh-indexer-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
